services:
  overseerr:
    build:
      context: https://github.com/Tw1zT3d2four7/Overseerr.git#overseer-with-lidarr-support
      args:
        COMMIT_TAG: bb1a14e
    ports:
      - 5055:5055
    volumes:
      - /PATH/TO/YOUR/OVERSEER/config:/app/config
